link:index.adoc[Index]

== Java 8: reading a file into a String

[source,java]
----
String content = new String(Files.readAllBytes(Paths.get("duke.java")));
----


== Derby on Glassfish
To work around security issue occuring since Java7u51:

asadmin start-database --dbport 55000
and
asadmin stop-database --dbport 55000
(default port is 1527)
And then in the glassfish admin console (http://localhost:4848/common/index.jsf) under
Resources/JDBC/JDBC Connection Pools/Derby Pool  --> Tab 'Additional Properties': change 'PortNumber' to 55000

more radical: in /home/sven/tools/glassfish4/javadb/bin call: startNetworkServer -noSecurityManager

For details see:
see http://stackoverflow.com/questions/21154400/unable-to-start-derby-database-from-netbeans-7-4


== Groovy metaClass per instance/class

http://stackoverflow.com/questions/4781936/dynamically-add-a-property-or-method-to-an-object-in-groovy



== HTML5

=== Divs next to each other

[source,html]
----

    <div>
        <div style="display: inline-block">
            Left
        </div>
        <div style="display: inline-block">
            Right
        </div>
    </div>

----

== Misc
=== Ubuntu
- control sound: pavucontrol


== VoIP-Anschluss
Menü -> Basis einstellen -> Einstellungen -> System Einstellungen -> Sonderfunktion -> Wahlmerkmale -> Autom. Keypad (aktivieren).
Codes: http://hilfe.telekom.de/hsp/cms/content/HSP/de/3378/faq-445419652#k

== Unix

find files modified at a certain date (see http://stackoverflow.com/questions/158044/how-to-use-find-to-search-for-files-created-on-a-specific-date)
[source,bash]
----
find . -name "*.js" -newermt 2014-05-22 ! -newermt 2014-05-23 |xargs ls -l
----

== JavaFX

* AfterburnerFX ControllerFactory: https://github.com/AdamBien/afterburner.fx/blob/master/src/main/java/com/airhacks/afterburner/views/FXMLView.java#L85
